# Generated by Django 5.1.6 on 2025-03-06 04:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.CharField(choices=[('KSU', 'KSU'), ('SFI', 'SFI'), ('ABVP', 'ABVP'), ('NOTA', 'NOTA')], help_text='The candidate for whom the vote was cast.', max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='The time when the vote was cast.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.OneToOneField(help_text='The voter who cast this vote.', on_delete=django.db.models.deletion.CASCADE, to='voting_app.voter'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='encrypted_face_data',
            field=models.BinaryField(help_text='Encrypted face data of the voter.'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='has_voted',
            field=models.BooleanField(default=False, help_text='Indicates whether the voter has cast a vote.'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='ktu_id',
            field=models.CharField(help_text='Enter the KTU ID in the format TVE22CS followed by 3 digits (e.g., TVE22CS001).', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='KTU ID must be in the format TVE22CS followed by 3 digits (e.g., TVE22CS001).', regex='^TVE22CS\\d{3}$')]),
        ),
    ]
